---
- name: Having a website with Hello World and using apache2
  hosts: WebsiteServer
  become: yes
  remote_user: azureuser


  tasks:
    - name: Install of apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: put the index.html
      ansible.builtin.copy:
        src: ../template/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
      
    - name: Replace the existant public with no passphrase by a a public key with passphrase
      ansible.builtin.copy:
        src: ../template/id_rsa.pub
        dest: /home/azureuser/.ssh/id_rsa.pub
        owner: azureuser
        group: azureuser
        mode: '0600'